image: gitlab/dind

stages:
  - test
  - build

variables:
  COMPOSE_HTTP_TIMEOUT: "600"

test:
  stage: test
  script:
    - docker-compose -f ./docker/docker-compose.ci.yml run --rm app make

build:
  stage: build
  script:
    - export REGISTRY=registry.gitlab.com
    - export IMAGE="$REGISTRY/$(basename $(dirname $PWD))/$(basename $PWD)"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build --rm -t $IMAGE:latest -f docker/Dockerfile.production .
    - docker push $IMAGE:latest
