image: gitlab/dind

stages:
  - test
  - build

test:
  stage: test
  variables:
    COMPOSE_HTTP_TIMEOUT: "600"
    RAILS_ENV: test
  script:
    - apt-get update -qq
    - apt-get install -y make
    - make setup
    - make test

build:
  stage: build
  script:
    - export REGISTRY=registry.gitlab.com
    - export IMAGE="$REGISTRY/$(basename $(dirname $PWD))/$(basename $PWD)"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build --rm -t $IMAGE:latest -f docker/Dockerfile.production .
    - docker push $IMAGE:latest
