image: docker:git

services:
  - docker:dind

stages:
  - build
  - release

before_script:
  - export REGISTRY=registry.gitlab.com
  - export IMAGE="$REGISTRY/$(basename $(dirname $PWD))/$(basename $PWD)"
  - export TAG=$CI_BUILD_REF_NAME
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY

build:
  stage: build
  script:
    - echo "Start build image $IMAGE:$TAG"
    - ./bin/build
    - docker push $IMAGE:$TAG

release:
  stage: release
  only:
    - master@shiplix/shiplix
  script:
    - docker pull $IMAGE:$TAG
    - docker tag $IMAGE:$TAG $IMAGE:latest
    - docker push $IMAGE:latest
