source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'rails-i18n'
gem 'dotenv-rails'
gem 'pg'
gem 'pg_array_parser'
gem 'sass-rails', '~> 4.0.3'
gem 'less-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'haml'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'autoprefixer-rails'
gem 'will_paginate-bootstrap'
gem 'twitter-bootswatch-rails', '~> 3.2'
gem 'twitter-bootswatch-rails-helpers', '~> 3.1'
gem 'twitter-bootswatch-rails-fontawesome'
gem 'draper'
gem 'bootstrap_form'
gem 'vicar', '~> 0.0.2'
gem 'foreigner', '~> 1.6'
gem 'seedbank'
gem 'multi_json'
gem 'oj'
gem 'aasm', '~> 4.0'
gem 'redis', '~> 3.1'
gem 'hiredis', '~> 0.5'
gem 'dalli', '~> 2.7'
gem 'rails-cache-tags', '~> 1.3'
gem 'redis-mutex', '~> 3.0'
gem 'omniauth-github'
gem 'attr_extras'
gem 'resque', '~> 1.25'
gem 'resque-retry'
gem 'resque-god'
gem 'resque-single'
gem 'octokit'
gem 'pluggable_js'
gem 'font-awesome-rails'
gem 'cocaine', require: false
gem 'flog', '~> 4.3'
gem 'parser', '~> 2.1'
gem 'reek', '~> 1.6'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'capistrano', '~> 3.2'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano3-puma'
  gem 'quiet_assets'
  gem 'wirble'
end

group :production, :development do
  gem 'puma'
end

group :test do
  gem 'timecop', '~> 0.7'
  gem 'rspec-rails', '~> 3.1'
  gem 'rspec-given', '~> 3.5'
  gem 'test_after_commit', '~> 0.4'
  gem 'mock_redis', :github => 'causes/mock_redis'
  gem 'factory_girl_rails', '~> 4.4'
  gem 'shoulda-matchers', '~> 2.7'
  gem 'simplecov', '~> 0.9'
end
