version: '2'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: shiplix_app
    environment:
      - RAILS_ENV=$RAILS_ENV
      - SHIPLIX_HOST=shiplix.dev
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg
      - redis
      - cache

  nginx:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: shiplix_app
    environment:
      - VIRTUAL_HOST=shiplix.dev
      - RAILS_ENV=$RAILS_ENV
      - SHIPLIX_HOST=shiplix.dev
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - nginx
      - pg
      - redis
      - cache

  worker:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: shiplix_app
    environment:
      - RAILS_ENV=$RAILS_ENV
      - SHIPLIX_HOST=shiplix.dev
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg
      - redis
      - cache

  pg:
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    volumes:
      - redis-data:/data

  cache:
    environment:
      - REDIS_MAXMEMORY=30mb

volumes:
  ruby-gems:
    external:
      name: gems-ruby2

  pg-data:
    driver: local

  redis-data:
    driver: local
