version: '2'

services:
  app:
    extends:
      file: docker-compose.common.yml
      service: app
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg
      - redis
      - cache

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    extends:
      file: docker-compose.common.yml
      service: web
    environment:
      - VIRTUAL_HOST=shiplix.dev
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - nginx
      - pg
      - redis
      - cache

  worker:
    extends:
      file: docker-compose.common.yml
      service: worker
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg
      - redis
      - cache

  pg:
    extends:
      file: docker-compose.common.yml
      service: pg
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis
    volumes:
      - redis-data:/data

  cache:
    extends:
      file: docker-compose.common.yml
      service: cache
    environment:
      - REDIS_MAXMEMORY=30mb

volumes:
  ruby-gems:
    driver: local

  pg-data:
    driver: local

  redis-data:
    driver: local
