version: '2'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.${COMPOSE_FILE_EXT}
    command: bash
    environment:
      - SHIPLIX_HOST=${SHIPLIX_HOST}
      - SHIPLIX_POSTGRES_URL=postgres://postgres@pg/shiplix
      - SHIPLIX_REDIS_URL=redis://redis:6379
      - SHIPLIX_CACHE_URL=redis://cache:6379

  web:
    extends:
      service: app
    command: bundle exec rails s Puma -b 0.0.0.0 -p 80
    expose:
      - "80"

  worker:
    extends:
      service: app
    environment:
      - 'QUEUE=*'
    command: 'bundle exec rake resque:work --trace'

  pg:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=shiplix

  redis:
    image: redis:3-alpine
    command: 'redis-server --appendonly yes --bind 0.0.0.0'

  cache:
    image: redis:3-alpine
    environment:
      - REDIS_MAXMEMORY=30mb
    command: 'redis-server --bind 0.0.0.0 --maxmemory $$REDIS_MAXMEMORY --maxmemory-policy allkeys-lru'
