version: '2'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: shiplix_app
    command: make
    environment:
      - RAILS_ENV=test
      - SHIPLIX_HOST=shiplix.dev
      - SHIPLIX_STRIPE_PUBLISHABLE_KEY=stripe_key
      - SHIPLIX_STRIPE_SECRET_KEY=stripe_secret
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg

  pg:
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  ruby-gems:
    driver: local

  pg-data:
    driver: local
