version: '2'

services:
  app:
    environment:
      - BUNDLE_PATH=/bundle/2.3
      - RAILS_ENV=$RAILS_ENV
    volumes:
      - ..:/app
      - bundler-data:/bundle
    depends_on:
      - pg
      - redis
      - cache

  web:
    environment:
      - BUNDLE_PATH=/bundle/2.3
      - RAILS_ENV=$RAILS_ENV
    volumes:
      - ..:/app
      - bundler-data:/bundle
    depends_on:
      - pg
      - redis
      - cache
    labels:
      com.dnsdock.name: "shiplix"
      com.dnsdock.image: ""

  worker:
    environment:
      - BUNDLE_PATH=/bundle/2.3
      - RAILS_ENV=$RAILS_ENV
    volumes:
      - ..:/app
      - bundler-data:/bundle
    depends_on:
      - pg
      - redis
      - cache

  pg:
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    volumes:
      - redis-data:/data

  cache:
    environment:
      - REDIS_MAXMEMORY=30mb

volumes:
  bundler-data:
    external:
      name: bundler_data

  pg-data:
    driver: local

  redis-data:
    driver: local
