version: '2'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: shiplix_app
    env_file:
      - ./.env.development
    environment:
      - RAILS_ENV=$RAILS_ENV
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg
      - redis
      - cache

  worker:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: shiplix_app
    env_file:
      - ./.env.development
    environment:
      - 'QUEUE=*'
      - RAILS_ENV=$RAILS_ENV
    volumes:
      - ..:/app
      - ruby-gems:/gems
    depends_on:
      - pg
      - redis
      - cache

  pg:
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    volumes:
      - redis-data:/data

  cache:
    environment:
      - REDIS_MAXMEMORY=30mb

volumes:
  ruby-gems:
    external:
      name: gems-ruby2

  pg-data:
    driver: local

  redis-data:
    driver: local
