web:
  extends:
    file: docker-compose.common.yml
    service: web
  image: registry.gitlab.com/shiplix/shiplix:latest
  command: bash -c "rake db:migrate && unicorn -c /app/config/unicorn.rb -E deployment"
  environment:
    - KONTENA_LB_INTERNAL_PORT=3000
    - SHIPLIX_POSTGRES_URL=postgres://postgres@${project}-pg/shiplix
    - SHIPLIX_REDIS_URL=redis://${project}-redis:6379
    - SHIPLIX_REDIS_CACHE_URL=redis://${project}-redis_cache:6379
  secrets:
    - secret: SHIPLIX_LB_HOSTS
      name: KONTENA_LB_VIRTUAL_HOSTS
      type: env
    - secret: SHIPLIX_HOST
      name: SHIPLIX_HOST
      type: env
    - secret: SHIPLIX_GITHUB_SECRET_TOKEN
      name: GITHUB_SECRET_TOKEN
      type: env
    - secret: SHIPLIX_GITHUB_CLIENT_ID
      name: SHIPLIX_GITHUB_CLIENT_ID
      type: env
    - secret: SHIPLIX_GITHUB_CLIENT_SECRET
      name: SHIPLIX_GITHUB_CLIENT_SECRET
      type: env
    - secret: SHIPLIX_SECRET_KEY_BASE
      name: SHIPLIX_SECRET_KEY_BASE
      type: env
    - secret: SHIPLIX_NEWRELIC_KEY
      name: SHIPLIX_NEWRELIC_KEY
      type: env
    - secret: SHIPLIX_NEWRELIC_APP_NAME
      name: SHIPLIX_NEWRELIC_APP_NAME
      type: env
  external_links:
    - lb
  log_driver: syslog
  log_opt:
    tag: '{{.Name}}'

worker:
  extends:
    service: worker
  environment:
    - 'QUEUE=*'
    - SHIPLIX_POSTGRES_URL=postgres://postgres@${project}-pg/shiplix
    - SHIPLIX_REDIS_URL=redis://${project}-redis:6379
    - SHIPLIX_REDIS_CACHE_URL=redis://${project}-redis_cache:6379
  secrets:
    - secret: SHIPLIX_LB_HOSTS
      name: KONTENA_LB_VIRTUAL_HOSTS
      type: env
    - secret: SHIPLIX_HOST
      name: SHIPLIX_HOST
      type: env
    - secret: SHIPLIX_GITHUB_SECRET_TOKEN
      name: GITHUB_SECRET_TOKEN
      type: env
    - secret: SHIPLIX_GITHUB_CLIENT_ID
      name: SHIPLIX_GITHUB_CLIENT_ID
      type: env
    - secret: SHIPLIX_GITHUB_CLIENT_SECRET
      name: SHIPLIX_GITHUB_CLIENT_SECRET
      type: env
    - secret: SHIPLIX_SECRET_KEY_BASE
      name: SHIPLIX_SECRET_KEY_BASE
      type: env
    - secret: SHIPLIX_NEWRELIC_KEY
      name: SHIPLIX_NEWRELIC_KEY
      type: env
    - secret: SHIPLIX_NEWRELIC_APP_NAME
      name: SHIPLIX_NEWRELIC_APP_NAME
      type: env
    - secret: SHIPLIX_STRIPE_SECRET_KEY
      name: SHIPLIX_STRIPE_SECRET_KEY
      type: env
    - secret: SHIPLIX_STRIPE_PUBLISHABLE_KEY
      name: SHIPLIX_STRIPE_PUBLISHABLE_KEY
      type: env
  volumes:
    - '/tmp/builds:/app/tmp/builds'
  log_driver: syslog
  log_opt:
    tag: '{{.Name}}'

pg:
  extends:
    file: docker-compose.common.yml
    service: pg
  stateful: true
  log_driver: syslog
  log_opt:
    tag: '{{.Name}}'

redis:
  extends:
    file: docker-compose.common.yml
    service: redis
  stateful: true
  log_driver: syslog
  log_opt:
    tag: '{{.Name}}'

redis_cache:
  extends:
    file: docker-compose.common.yml
    service: redis_cache
  log_driver: syslog
  log_opt:
    tag: '{{.Name}}'
