defaults: &DEFAULTS
  adapter: postgresql
  username: <%= ENV.fetch("SHIPLIX_DB_USER", "shiplix") %>
  host: <%= ENV.fetch("SHIPLIX_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("SHIPLIX_DB_PORT", 5432) %>
  password: <%= ENV["SHIPLIX_DB_PASSWORD"] %>

development:
  <<: *DEFAULTS
  database: shiplix

test:
  <<: *DEFAULTS
  database: shiplix_test

production:
  <<: *DEFAULTS
  database: shiplix
