defaults: &DEFAULTS
  servers: '<%= ENV["SHIPLIX_MEMCACHE_SERVERS"] %>'
  namespace: 'shiplix'
  autofix_keys: true

development:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS
  namespace: 'shiplix_test'
