defaults: &DEFAULTS
  host: '<%= ENV.fetch("SHIPLIX_REDIS_HOST", "redis") %>'
  port: <%= ENV.fetch("SHIPLIX_REDIS_PORT", 6379) %>
  namespace: 'shiplix'
  driver: hiredis

development:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
