#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
set -vx

CONFIG_PATH=./config/docker/production

# build rails
docker build -t shiplix/rails -f $CONFIG_PATH/rails/Dockerfile .

# get compiled assets
rm -rf ./public/assets
mkdir ./public/assets
docker run --rm -v $(pwd)/public/assets:/data shiplix/rails bash -c 'cp -r ./public/assets/* /data'

# build nginx
docker build -t shiplix/nginx -f $CONFIG_PATH/nginx/Dockerfile .

# push images
docker push shiplix/rails
docker push shiplix/nginx
